version: "3.7"

services:
  web:
    image: pbh/webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8010:8020"
    volumes:
      - "./:/opt/app/WebApp"
      - "static_volume:/opt/app/WebApp/static"
    env_file: ./blog/.env

  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - "static_volume:/opt/app/WebApp/static:ro"
    ports:
      - "8001:80"
    env_file: ./nginx/.env
    depends_on:
      - web

volumes:
  static_volume:
