version: "3.7"

services:

  db:
    image: postgres:12.7-alpine3.14
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - 'psql_volume:/var/lib/postgresql/data'
    env_file: ./blog/.env
    networks:
      - web_app_network

  web:
    image: pbh/webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8010:8020"
    volumes:
      - "./:/opt/app/WebApp"
      - "static_volume:/opt/app/WebApp/static"
    env_file: ./blog/.env
    networks:
      - web_app_network
    depends_on:
      - db

  nginx:
    image: nginx:1.21.0-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/certs
      - "static_volume:/opt/app/WebApp/static:ro"
    ports:
      - "8001:80"
    env_file: ./nginx/.env
    depends_on:
      - web
    networks:
      - web_app_network

volumes:
  static_volume:
  psql_volume:

networks:
  web_app_network:
