# Generated by Django 3.1.2 on 2020-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='blog.PostTagBase'),
        ),
    ]
